config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: 'events#index'
resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :image
  attr_accessor :selected_color

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @events = Event.all
    @event = Event.new(event_params)
    @event.color = params[:event][:color]

    if @event.save
      redirect_to events_path, notice: "イベントを作成しました"
    else
      flash.now[:notice] = "イベント名を入力してください"
      render 'events/index'
    end
  end


  def destroy
   @event = Event.find(params[:id])
   @event.destroy
   redirect_to events_path, notice:"削除しました"
  end



  private

  def event_params
    params.require(:event).permit(:title, :content, :start_time, :color, :image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="toppage">
<h1 class="top">Calendar</h1>
<br>

<div class="row">
<div class="col-md-4">
	<div class="schedule">今後の予定一覧</div>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th>タイトル</th>
      <th>日程</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.title , event %></td>
        <td><%= event.start_time.strftime("%m-%d") %></td>
        <td>
          <%= image_tag @event.image if @event.image.attached? %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<%= form_with(model: @event, local: true) do |form| %>
  <div class="title">
    <div class="form-tag">イベント名</div>
    <%= form.text_field :title, id: 'event-title' %>
  </div>

  <div class="content">
    <div class="form-tag">内容</div>
    <%= form.text_field :content %>
  </div>


  <div>
    <div class="form-tag">カラー</div>
  <select id="color-selector" name="event[color]">
    <option value="red" class="red-bg">赤</option>
    <option value="blue" class="blue-bg">青</option>
    <option value="green" class="green-bg">緑</option>
    <option value="yellow" class="yellow-bg">黄</option>
  </select>
</div>


 <script>
document.addEventListener('DOMContentLoaded', function() {
  const colorSelector = document.getElementById('color-selector');

  colorSelector.addEventListener('change', function() {
    const selectedOption = colorSelector.options[colorSelector.selectedIndex];
    const selectedColor = selectedOption.value;

  // 項目の背景色を設定
    colorSelector.style.backgroundColor = selectedColor;
  });

  // 初期の背景色を設定
  const initialOption = colorSelector.options[colorSelector.selectedIndex];
  const initialColor = initialOption.value;
  colorSelector.style.backgroundColor = initialColor;

  // 各選択肢の背景色を設定
  const options = colorSelector.querySelectorAll('option');
  options.forEach(function(option) {
    const optionColor = option.value;
    option.style.backgroundColor = optionColor;
  });
});

 </script>

  <div class="time">
    <div class="form-tag">時間</div>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="image">
    <div>image</div>
    <%= form.file_field :image %>
  </div>

  <div class="submit">
    <%= form.submit 'イベントを作成' %>
  </div>
<% end %>

<div class="col-md-8">
  <%= month_calendar events: @events do |date, events| %>
    <%= date.day %>

    <% events.each do |event| %>
   <div>
  <span class="event-title" style="color: <%= event.color %>;">
      <span class="event-badge <%= event.color %>">●</span>
      <%= link_to event.title, event %>
    </span>
    </div>
    <% end %>
  <% end %>
</div>


</div>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show">
<p>
  <strong>タイトル</strong>
  <%= @event.title %>
</p>

<p>
  <strong>詳細</strong>
  <%= @event.content %>
</p>

<p>
  <strong>日時</strong>
  <%= @event.start_time.strftime("%m-%d %H:%M") %>
</p>
<% if @event.image.attached? %>
  <%= image_tag @event.image,size: "300x300" %>
<% end %>

<%= link_to '消去',event_path(@event.id), method: :delete, data: { confirm: '本当に?' } %>
<%= link_to '戻る', events_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calender</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <strong><span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span></strong>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day), 'data-date' => day.to_s do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>